name: Nutpam Madal
description: "A Tamil newsletter on science, technology, engineering and maths by Tharique Azeez. Dispatched every Tuesday. "
pygments: false

permalink : /:title.html

encoding  : utf-8

markdown  : kramdown
